### PR TITLE
Support for older devices and restoring config file

### PR DESCRIPTION
**Pull request by ayushin**

### CODE REVIEW

**Comment by mcw0** [comment]
Cool, thanks man.

**Comment by uggabugga12** [comment]
@ayushin, @mcw0 do you have a solution for `Service [console] not available on remote device`? All requests are getting the same response, such as 
`[listService] {'id':1, 'params': None, 'result': False}`

**Comment by ayushin** [comment]
You need to play with all kind of combinations of the logon/username/password depending on the version of the firmware.

I am not really into this hardware, was just a side home project I could not leave alone

**Comment by uggabugga12** [comment]
@ayushin thanks for replying. I have tried that. However, using 3des does not seem to work at all for me regardless of which logon I'm using. it's possible to login but after that it's not doing too hot

**Pull request merged**
